### ISSUE TITLE
Excellent work~

### ISSUE THREAD

**Issue by PkuRainBow** [zhuangyqin/DRN#1]
Hi, I am wondering whether you have interest to intern at VC group of msra. Please send me your CV to (yuyua@microsoft.com) if you have interest.  We are also focused on Semantic Segmentation.

**Comment by yjl9122** [comment]
So interesting issue.
Hi, we are also focused on Semantic Segmentation at machine learning lab of samsung. We got 2nd place on Pascal VOC leaderboard. If you have interest, please send me your CV to me. (jlong.yuan@samsung.com)

**Comment by yjl9122** [comment]
So interesting issue.
@zhuangyqin 
Hi, we are also focused on Semantic Segmentation at machine learning lab of samsung. We got 2nd place on Pascal VOC leaderboard. If you have interest, please send me your CV to me. (jlong.yuan@samsung.com)
