### ISSUE TITLE
Empty repository

### ISSUE THREAD

**Issue by ChristianEschen** [zhuangyqin/DRN#2]
Your repository appears empty.
You have attached a github repository to cityscapes, but however the repository appears empty. Maybe there is something wrong?

**Comment by zhuangyqin** [comment]
Not wrong, Because I am busy to do this work for public, I link this to my rep when the code is complete .

**Comment by zhanghang1989** [comment]
Hi @zhuangyqin , nice work. Could you please provide the link to your papers for this work? Thanks!

**Comment by zhuangyqin** [comment]
@zhanghang1989 ,  you can give me your email, and  I will email to you.

**Comment by KevinSunUC** [comment]
Hello @zhuangyqin , Could you send me your paper about this work? My Email is weiwei.sun3@gmail.com
I really appreciate your kindness.

**Comment by zhanghang1989** [comment]
zhanghang0704@gmail.com Thanks

**Comment by Hv0nnus** [comment]
Hi @zhuangyqin , great result on Cityscape. I would be grateful if you could send me your paper associated. tanguy.kerdoncuff612@gmail.com
Thank you in advance

**Comment by ChristianEschen** [comment]
Hi 
I would like to see the paper as well.
christian_Eschen@hotmail.com

thank you

**Comment by tkingcer** [comment]
Hi @zhuangyqin, nice work! I am very interested in your work. Could you kindly send me a copy of your paper to my email tkingcer@gmail.com. Many thanks.

**Comment by John1231983** [comment]
Great. My email is john1231983@gmail.com. thanks so much

**Comment by chowkamlee81** [comment]
Hi @zhuangyqin , kindly send me the paper to my mail id chowkamlee81@gmail.com, since the work is very much interesting. Kindly do the needful.

**Comment by ChayaBei** [comment]
Hi
I would like to see the paper as well.

15060401005@pop.zjgsu.edu.cn

thank you very very much

**Comment by VisionTheta** [comment]
xutong6@mail2.sysu.edu.cn, thanks.

**Comment by zxJohnFly** [comment]
Hi @zhuangyqin , great work. I would like to read your paper. This is my email johnfly2000@gmail.com，Thank you.

**Comment by Paranoidv** [comment]
very good work
I would like to see the paper as well.
my email : 893457818@qq.com
thank you!!

**Comment by CelineChen95** [comment]
Hi @zhuangyqin 
very good work
I would like to read the paper as well.
my email : 503405834@qq.com
thank you!!

**Comment by tianhaijie** [comment]
Great work! @zhuangyqin 
Can you please send me your paper about this work?  
My email is a1831974703@163.com 
Thank u very much!

**Comment by nurhadiyatna** [comment]
hi, @zhuangyqin  could you please send me your paper as well to my e-mail, I would love to read your great work. I saw  you have two papers : 
1. Dense Relation Network: Learning Consistent and Context-Aware Representation For Semantic Image Segmentation
2. RelationNet: Learning Deep-Aligned Representation for Semantic Image Segmentation

Could you please send me both of them? here is my e-mail: adinurhadiyatna@gmail.com 

Thank you in advance, 

Regards,

**Comment by CelineChen95** [comment]
@Hv0nnus  Did anthor send his paper to you? I have sent email to him,but no  reply .

**Comment by chowkamlee81** [comment]
No reply from author till now
